# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'victoria.vassileva@yahoo.fr'
  config.password       = 'Missmanga1996'
  config.integrator_key = '37b469c5-4090-44bd-a7a8-b4bc118292e5'
  config.account_id     = '9242773'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
end

